# Numpy:
*   NumPy (Numerical Python) is a powerful library in Python for numerical computing.
*   It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these data structures efficiently.



#Install numpy:

In [ ]:
!pip install numpy

Import numpy:

In [ ]:
import numpy as np

In [ ]:
a = np.array ([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


#Create a array of zero:

In [ ]:
np.zeros((2,4))  #np.zeros(no.of_rows , no.of_columns)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#Create a array of ones:

In [ ]:
np.ones((3,2,4))  #np.ones((shape_of_the_dimention , no.of_rows , no.of_columns))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

#Create a array of evenly spaced values(using step value):

In [ ]:
d = np.arange(1,20,5)     #variable = np.arange(starting_value , ending_value , step_size)
print(d)

[ 1  6 11 16]


In [ ]:
e = np.arange(1,1000,10)
print(e)

[  1  11  21  31  41  51  61  71  81  91 101 111 121 131 141 151 161 171
 181 191 201 211 221 231 241 251 261 271 281 291 301 311 321 331 341 351
 361 371 381 391 401 411 421 431 441 451 461 471 481 491 501 511 521 531
 541 551 561 571 581 591 601 611 621 631 641 651 661 671 681 691 701 711
 721 731 741 751 761 771 781 791 801 811 821 831 841 851 861 871 881 891
 901 911 921 931 941 951 961 971 981 991]


#Create a array of evenly spaced values(no.of samples):

In [ ]:
f = np.linspace(1,2,15)    #variable = np.linspace(starting_value , endling_value , No.of_samples)
print(f)

[1.         1.07142857 1.14285714 1.21428571 1.28571429 1.35714286
 1.42857143 1.5        1.57142857 1.64285714 1.71428571 1.78571429
 1.85714286 1.92857143 2.        ]


#Create a constant array:

In [ ]:
g = np.full((4),2)   # variable = np.full((no.of_column),value_need to be stored in array)
print(g)             #1D array

[2 2 2 2]


In [ ]:
h = np.full((2,3),2)  # variable = np.full((no.of_rows,no.of_column),value_need to be stored in array)
print(h)              #2D array

[[2 2 2]
 [2 2 2]]


In [ ]:
i = np.full((3,3,4),2)  # variable = np.full((no.of_dimention,no.of_rows,no.of_column),value_need to be stored in array)
print(i)                #3D array

[[[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]


#Create a identity matrix:

In [ ]:
j = np.eye(2)  #variable = np.eye(no.of_rows)
print(j)

[[1. 0.]
 [0. 1.]]


#Create a array with random values:

In [ ]:
k = np.random.random((2,2))  #variable = np.random.random((no.of_rows,no.of_column))
print(k)

[[0.2042871  0.49170766]
 [0.62966284 0.54882619]]


#Shape of an array:

In [ ]:
l = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(l)
print(l.shape)      #(no.of_rows , no.of_columns)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


#Find no.of elements in a array:

In [ ]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(m.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


#Find length of the array:

In [ ]:
n = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]]])
print(n)
print(n.shape)
len(n)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)


1

#Access array elements:

Access 1D array elements using index value:

In [ ]:
o = np.array([1,2,3,4,5,6])
print(o)
print(o[0])

[1 2 3 4 5 6]
1


Access 2D array elements using index values:

In [ ]:
p = np.array([[1,2,3],[4,5,6]])
print(p)
print(p[1,2])     #print( variable_name [index of 1D array , index of value])

[[1 2 3]
 [4 5 6]]
6


Access 3D array using index value:

In [ ]:
q = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(q)
print()

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]



#Data types in numpy
1. i - integer
2. b - boolean
3. f - float
4. c - complex
5. M - Datetime
6. O - object
7. S - string


In [ ]:
r = np.array([1,2,3])
print(r)
print(r.dtype)

[1 2 3]
int64


In [ ]:
#type convertion int to float
s = np.array([1,2,3],dtype='f')
print(s)
print(s.dtype)

[1. 2. 3.]
float32


In [ ]:
#type convertion int to complex
t = np.array([1,2,3],dtype='c')
print(t)
print(t.dtype)

[b'1' b'2' b'3']
|S1


In [ ]:
#type conertion int to boolean using as parameter
u = np.array([0,1,2,3])
v = u.astype(bool)
print(v)
print(v.dtype)

[False  True  True  True]
bool


#Copy Method:

*   The .copy() method is used to create a deep copy of an array.
*   This means that the copied array has its own separate memory location, and changes to the original array do not affect the copied array.



In [ ]:
w = np.array([1,2,3,4,5])
x = w.copy()
print("w=",w)
w[2]= 6
print("w=",w)
print("x=",x)

w= [1 2 3 4 5]
w= [1 2 6 4 5]
x= [1 2 3 4 5]


#View Method:


*   The .view() method creates a shallow copy (or view) of an array.
*   This means that the new array shares the same data as the original array but has a different object identity.
*     Any modifications made to one array will affect the other.





In [ ]:
y = np.array([1,2,3,4,5])
z = y.view()
print("y=",y)
print("z=",z)
y[2]= 6
z[3]= 7
print("y=",y)
print("z=",z)

y= [1 2 3 4 5]
z= [1 2 3 4 5]
y= [1 2 6 7 5]
z= [1 2 6 7 5]


#Reshaping array:


In [ ]:
#Convert 1D into 2D
a = np.array([1,2,3,4,5,6,7,8,9])
print("a:\n",a)
print("size of a:",a.size)
b = a.reshape(3,3)
print("b:\n",b)

a:
 [1 2 3 4 5 6 7 8 9]
size of a: 9
b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#convert 1D into 3D
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("a:\n",a)
b = a.reshape(3,2,2)
print("b:\n",b)

a:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
b:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
#convert 2D into 3D
a = np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]])
print("a:\n",a)
b = a.reshape(2,2,4)
print("b:\n",b)

a:
 [[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
b:
 [[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


#Arthmetic operations:

In [ ]:
a = np.array([1,2,3])
b = np.array([5,6,7])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.sqrt(a))
print(np.sqrt(b))

[ 6  8 10]
[-4 -4 -4]
[ 5 12 21]
[0.2        0.33333333 0.42857143]
[1.         1.41421356 1.73205081]
[2.23606798 2.44948974 2.64575131]


#Slicing Method:


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[1:6])

[2 3 4 5 6]


In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1,1:4])   #variable(index of 1D array , starting index , ending index)

[7 8 9]


In [ ]:
a = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],

               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

print(a)
print(a[0,2,2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
9
